"""Verifier for goal: discover-gpu-catalog

Generated by pilot from the goal's evidence list. Deterministic
checks are real tests; `manual` evidence compiles to a FAILING
test so an unreviewed verifier cannot silently pass — replace each
TODO(team) with a real assertion before trusting results.
"""

import subprocess
from pathlib import Path

import pytest

def test_file_exists_0():
    """`/app/notes/gpu-catalog.md` exists"""
    assert Path('/app/notes/gpu-catalog.md').exists()


def test_file_contains_1():
    """`/app/notes/gpu-catalog.md` mentions 'http'"""
    path = Path('/app/notes/gpu-catalog.md')
    assert path.exists()
    assert 'http'.lower() in path.read_text().lower()


def test_manual_2():
    """The recorded URL is a live official page and the example GPU types actually appear on it."""
    pytest.fail(
        "TODO(team): replace with a real check: "
        'The recorded URL is a live official page and the example GPU types actually appear on it.'
    )
