"""Verifier for goal: understand-noninteractive-auth

Generated by pilot from the goal's evidence list. Deterministic
checks are real tests; `manual` evidence compiles to a FAILING
test so an unreviewed verifier cannot silently pass — replace each
TODO(team) with a real assertion before trusting results.
"""

import subprocess
from pathlib import Path

import pytest

def test_file_exists_0():
    """`/app/notes/auth-findings.md` exists"""
    assert Path('/app/notes/auth-findings.md').exists()


def test_file_contains_1():
    """`/app/notes/auth-findings.md` mentions 'login'"""
    path = Path('/app/notes/auth-findings.md')
    assert path.exists()
    assert 'login'.lower() in path.read_text().lower()


def test_manual_2():
    """The findings correctly state what the docs do and do not cover for headless auth; "not documented" is an acceptable, even expected, conclusion if the URLs checked are listed."""
    pytest.fail(
        "TODO(team): replace with a real check: "
        'The findings correctly state what the docs do and do not cover for headless auth; "not documented" is an acceptable, even expected, conclusion if the URLs checked are listed.'
    )
