"""Verifier for goal: execute-unauthenticated-surface

Generated by pilot from the goal's evidence list. Deterministic
checks are real tests; `manual` evidence compiles to a FAILING
test so an unreviewed verifier cannot silently pass — replace each
TODO(team) with a real assertion before trusting results.
"""

import subprocess
from pathlib import Path

import pytest

def test_cmd_ok_0():
    """`brev --help` exits successfully"""
    proc = subprocess.run(
        ["bash", "-lc", 'brev --help'],
        capture_output=True, text=True, timeout=120,
    )
    assert proc.returncode == 0, proc.stderr or proc.stdout


def test_file_exists_1():
    """`/app/notes/cli-surface.json` exists"""
    assert Path('/app/notes/cli-surface.json').exists()


def test_cmd_ok_2():
    """`python3 -c "import json; json.load(open('/app/notes/cli-surface.json'))"` exits successfully"""
    proc = subprocess.run(
        ["bash", "-lc", 'python3 -c "import json; json.load(open(\'/app/notes/cli-surface.json\'))"'],
        capture_output=True, text=True, timeout=120,
    )
    assert proc.returncode == 0, proc.stderr or proc.stdout
