"""Verifier for goal: understand-gpu-provisioning

Generated by pilot from the goal's evidence list. Deterministic
checks are real tests; `manual` evidence compiles to a FAILING
test so an unreviewed verifier cannot silently pass — replace each
TODO(team) with a real assertion before trusting results.
"""

import subprocess
from pathlib import Path

import pytest

def test_file_exists_0():
    """`/app/notes/provision-command.md` exists"""
    assert Path('/app/notes/provision-command.md').exists()


def test_file_contains_1():
    """`/app/notes/provision-command.md` mentions '--gpu'"""
    path = Path('/app/notes/provision-command.md')
    assert path.exists()
    assert '--gpu'.lower() in path.read_text().lower()


def test_manual_2():
    """The recorded command is syntactically valid per current docs (machine-type:gpu-type:count format) and the justification cites the doc page it came from."""
    pytest.fail(
        "TODO(team): replace with a real check: "
        'The recorded command is syntactically valid per current docs (machine-type:gpu-type:count format) and the justification cites the doc page it came from.'
    )
