"""Compile a lint-clean Spec into Harbor task directories.

Output mirrors what `harbor init --task` scaffolds (schema_version 1.3),
so anything Harbor's tooling accepts from its own scaffold it accepts from
ours. The difference is that instruction.md, tests, and metadata arrive
filled in from the goal instead of empty.
"""

from __future__ import annotations

import re
from pathlib import Path

from pilot.model import Evidence, Goal, Spec

TODO_MARKER = "TODO(team)"


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9-]+", "-", text.lower()).strip("-")


def _toml_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _task_toml(spec: Spec, goal: Goal) -> str:
    product = spec.product
    return f"""schema_version = "1.3"
artifacts = []

[task]
name = {_toml_str(f"{product.org}/{_slug(product.name)}-{_slug(goal.id)}")}
description = {_toml_str(goal.outcome.replace(chr(10), " ").strip())}
authors = []
keywords = ["agent-readiness", {_toml_str(goal.dimension)}]

[metadata]
pilot_goal_id = {_toml_str(goal.id)}
readiness_dimension = {_toml_str(goal.dimension)}
public_info_only = {str(goal.public_info_only).lower()}
product = {_toml_str(product.name)}

[verifier]
timeout_sec = {spec.verifier_timeout_sec}
collect = []

[verifier.env]

[agent]
timeout_sec = {spec.agent_timeout_sec}

[environment]
network_mode = "public"
build_timeout_sec = 600.0
os = "linux"
mcp_servers = []

[environment.env]

[solution.env]
"""


def _instruction(spec: Spec, goal: Goal) -> str:
    lines = [goal.outcome, ""]
    if goal.context:
        lines += [goal.context, ""]
    lines.append("You are working in a fresh Linux container with a shell.")
    if goal.public_info_only:
        lines.append(
            "Use only publicly available information — public docs, public "
            "repositories, public package registries. Do not assume access "
            "to internal wikis, support channels, or credentials beyond any "
            "provided in the environment."
        )
    # a file_contains bullet already implies existence of the same path
    contains_paths = {e.path for e in goal.evidence if e.kind == "file_contains"}
    shown: list[str] = []
    for e in goal.evidence:
        if e.kind == "file_exists" and e.path in contains_paths:
            continue
        d = e.describe_for_instruction()
        if d and d not in shown:
            shown.append(d)
    lines += [
        "",
        "When you are done, the following should be true:",
        *(f"- {d}" for d in shown),
        "",
        "Keep notes of what you tried in the files named above; the point is "
        "to show your working, not just the end state.",
    ]
    return "\n".join(lines) + "\n"


def _dockerfile(goal: Goal) -> str:
    lines = [
        "FROM ubuntu:24.04",
        "",
        "RUN apt-get update && apt-get install -y --no-install-recommends \\",
        "    curl ca-certificates git python3 \\",
        "    && rm -rf /var/lib/apt/lists/*",
        "",
        "WORKDIR /app",
        "RUN mkdir -p /app/notes",
    ]
    if goal.failure_injection:
        lines += [
            "",
            f"# {TODO_MARKER}: inject the broken state this recover goal starts from:",
            f"#   {goal.failure_injection}",
            "# e.g. plant an expired credential file, remove a dependency, or",
            "# point config at a dead endpoint. The agent must NOT be told.",
        ]
    return "\n".join(lines) + "\n"


# Same harness `harbor init --task` generates: pytest via uvx, CTRF report,
# reward.txt for Harbor's verifier.
_TEST_SH = """#!/bin/bash

# Installs test dependencies and runs the verifier.
# Copied to /tests/test.sh and run from the working directory.

apt-get update
apt-get install -y curl

curl -LsSf https://astral.sh/uv/0.9.7/install.sh | sh

source $HOME/.local/bin/env

uvx \\
  --with pytest==8.4.1 \\
  --with pytest-json-ctrf==0.3.5 \\
  pytest --ctrf /logs/verifier/ctrf.json /tests/test_outputs.py -rA

if [ $? -eq 0 ]; then
  echo 1 > /logs/verifier/reward.txt
else
  echo 0 > /logs/verifier/reward.txt
fi
"""


def _test_outputs(goal: Goal) -> str:
    header = [
        '"""Verifier for goal: ' + goal.id,
        "",
        "Generated by pilot from the goal's evidence list. Deterministic",
        "checks are real tests; `manual` evidence compiles to a FAILING",
        "test so an unreviewed verifier cannot silently pass — replace each",
        f"{TODO_MARKER} with a real assertion before trusting results.",
        '"""',
        "",
        "import subprocess",
        "from pathlib import Path",
        "",
        "import pytest",
        "",
    ]
    body: list[str] = []
    for i, e in enumerate(goal.evidence):
        name = f"test_{e.kind}_{i}"
        doc = e.describe().replace('"""', "'''")
        if e.kind == "cmd_ok":
            body += [
                f"def {name}():",
                f'    """{doc}"""',
                "    proc = subprocess.run(",
                f"        [\"bash\", \"-lc\", {e.cmd!r}],",
                "        capture_output=True, text=True, timeout=120,",
                "    )",
                "    assert proc.returncode == 0, proc.stderr or proc.stdout",
            ]
        elif e.kind == "file_exists":
            body += [
                f"def {name}():",
                f'    """{doc}"""',
                f"    assert Path({e.path!r}).exists()",
            ]
        elif e.kind == "file_contains":
            body += [
                f"def {name}():",
                f'    """{doc}"""',
                f"    path = Path({e.path!r})",
                "    assert path.exists()",
                f"    assert {e.text!r}.lower() in path.read_text().lower()",
            ]
        else:  # manual
            body += [
                f"def {name}():",
                f'    """{doc}"""',
                f"    pytest.fail(",
                f"        \"{TODO_MARKER}: replace with a real check: \"",
                f"        {e.note!r}",
                "    )",
            ]
        body.append("")
        body.append("")
    return "\n".join(header + body).rstrip() + "\n"


def _solution(goal: Goal) -> str:
    return (
        "#!/bin/bash\n\n"
        f"# {TODO_MARKER}: reference solution for goal '{goal.id}'.\n"
        "# Writing one is the fastest way to find out whether your own\n"
        "# docs are sufficient — if you can't script it from public info,\n"
        "# an agent can't either.\n"
    )


def task_dir_name(spec: Spec, goal: Goal) -> str:
    return f"{_slug(spec.product.name)}-{_slug(goal.id)}"


def compile_spec(spec: Spec, out_dir: Path) -> list[Path]:
    """Write one Harbor task dir per goal plus a dataset manifest."""
    out_dir.mkdir(parents=True, exist_ok=True)
    task_dirs: list[Path] = []

    for goal in spec.goals:
        task_dir = out_dir / task_dir_name(spec, goal)
        (task_dir / "environment").mkdir(parents=True, exist_ok=True)
        (task_dir / "tests").mkdir(exist_ok=True)
        (task_dir / "solution").mkdir(exist_ok=True)

        (task_dir / "task.toml").write_text(_task_toml(spec, goal))
        (task_dir / "instruction.md").write_text(_instruction(spec, goal))
        (task_dir / "environment" / "Dockerfile").write_text(_dockerfile(goal))
        (task_dir / "tests" / "test.sh").write_text(_TEST_SH)
        (task_dir / "tests" / "test_outputs.py").write_text(_test_outputs(goal))
        (task_dir / "solution" / "solve.sh").write_text(_solution(goal))
        task_dirs.append(task_dir)

    manifest = [
        f"# Agent-readiness dataset for {spec.product.name}, compiled by pilot.",
        "# Run locally:",
        f'#   harbor run -p "{out_dir.name}/*" -a claude-code -m <model>',
        "",
        "[dataset]",
        f"name = {_toml_str(f'{spec.product.org}/{_slug(spec.product.name)}-agent-readiness')}",
        f"description = {_toml_str(spec.product.summary)}",
        "authors = []",
        'keywords = ["agent-readiness"]',
        "",
    ]
    for task_dir in task_dirs:
        manifest += ["[[tasks]]", f"path = {_toml_str(task_dir.name)}", ""]
    (out_dir / "dataset.toml").write_text("\n".join(manifest))

    return task_dirs


def count_todos(task_dir: Path) -> int:
    return sum(
        p.read_text().count(TODO_MARKER)
        for p in task_dir.rglob("*")
        if p.is_file()
    )
