"""Verifier for goal: discover-install

Generated by pilot from the goal's evidence list. Deterministic
checks are real tests; `manual` evidence compiles to a FAILING
test so an unreviewed verifier cannot silently pass — replace each
TODO(team) with a real assertion before trusting results.
"""

import subprocess
from pathlib import Path

import pytest

def test_cmd_ok_0():
    """`brev --version` exits successfully"""
    proc = subprocess.run(
        ["bash", "-lc", 'brev --version'],
        capture_output=True, text=True, timeout=120,
    )
    assert proc.returncode == 0, proc.stderr or proc.stdout


def test_file_exists_1():
    """`/app/notes/install-source.md` exists"""
    assert Path('/app/notes/install-source.md').exists()


def test_manual_2():
    """/app/notes/install-source.md cites an official NVIDIA or Brev source (docs.nvidia.com or github.com/brevdev), not a third-party blog or a hallucinated URL."""
    pytest.fail(
        "TODO(team): replace with a real check: "
        '/app/notes/install-source.md cites an official NVIDIA or Brev source (docs.nvidia.com or github.com/brevdev), not a third-party blog or a hallucinated URL.'
    )
