"""Verifier for goal: recover-unauthenticated-error

Generated by pilot from the goal's evidence list. Deterministic
checks are real tests; `manual` evidence compiles to a FAILING
test so an unreviewed verifier cannot silently pass — replace each
TODO(team) with a real assertion before trusting results.
"""

import subprocess
from pathlib import Path

import pytest

def test_file_exists_0():
    """`/app/notes/recovery.md` exists"""
    assert Path('/app/notes/recovery.md').exists()


def test_file_contains_1():
    """`/app/notes/recovery.md` mentions 'brev login'"""
    path = Path('/app/notes/recovery.md')
    assert path.exists()
    assert 'brev login'.lower() in path.read_text().lower()


def test_manual_2():
    """The recovery plan quotes the actual error message observed and the remediation matches current docs; the trajectory shows no more than two retries of the failing command."""
    pytest.fail(
        "TODO(team): replace with a real check: "
        'The recovery plan quotes the actual error message observed and the remediation matches current docs; the trajectory shows no more than two retries of the failing command.'
    )
